name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake Animation
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Willians167
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake.gif

      - name: Push the snake files to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
