name: Generate Datas
on:
  # Atualiza o SVG todos os dias à meia-noite
  schedule:
    - cron: "0 0 * * *"
  # Permite execução manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Platane/snk@v2.0.0
      with:
        github_user_name: Willians167 # Substitua pelo seu nome de usuário
        outputs: dist/snake.svg

    - name: Commit and Push
      run: |
        git config --global user.name "Willians167"
        git config --global user.email "prwillians.costa@gmail.com"
        git add -A
        git commit -m "Generate snake animation"
        git push
Criar um Novo Arquivo de Workflow
Se você preferir criar um novo arquivo de workflow específico para a animação da cobrinha, você pode adicionar um novo arquivo YAML:

Crie um novo arquivo no diretório .github/workflows/ com um nome descritivo, por exemplo snake-animation.yml.

Adicione a configuração abaixo ao novo arquivo:

yaml
Copiar código
name: Generate Snake Animation

on:
  # Atualiza o SVG todos os dias à meia-noite
  schedule:
    - cron: "0 0 * * *"
  # Permite execução manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: Platane/snk@v2.0.0
      with:
        github_user_name: Willians167 # Substitua pelo seu nome de usuário
        outputs: dist/snake.svg

    - name: Commit and Push
      run: |
        git config --global user.name "Willians167"
        git config --global user.email "prwillians.costa@gmail.com"
        git add -A
        git commit -m "Generate snake animation"
        git push
